config/routes.rb
Rails.application.routes.draw do
  resources :sleep_alerts
  get 'welcome/index'
  root 'welcome#index'
  get 'welcome/clock'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sleep_alert.rb
class SleepAlert < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sleep_alerts_controller.rb
class SleepAlertsController < ApplicationController
  before_action :set_sleep_alert, only: [:show, :edit, :update, :destroy]

  # GET /sleep_alerts
  # GET /sleep_alerts.json
  def index
    @sleep_alerts = SleepAlert.all
  end

  # GET /sleep_alerts/1
  # GET /sleep_alerts/1.json
  def show
  end

  # GET /sleep_alerts/new
  def new
    @sleep_alert = SleepAlert.new
  end

  # GET /sleep_alerts/1/edit
  def edit
  end

  # POST /sleep_alerts
  # POST /sleep_alerts.json
  def create
    @sleep_alert = SleepAlert.new(sleep_alert_params)

    @sleep_alert.bed_time = @sleep_alert.wake_time - 9.hours

    respond_to do |format|
      if @sleep_alert.save
        format.html { redirect_to @sleep_alert, notice: 'Sleep alert was successfully created.' }
        format.json { render :show, status: :created, location: @sleep_alert }
      else
        format.html { render :new }
        format.json { render json: @sleep_alert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sleep_alerts/1
  # PATCH/PUT /sleep_alerts/1.json
  # def update
  #   respond_to do |format|
  #     if @sleep_alert.update(sleep_alert_params)
  #       format.html { redirect_to @sleep_alert, notice: 'Sleep alert was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @sleep_alert }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @sleep_alert.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /sleep_alerts/1
  # DELETE /sleep_alerts/1.json
  # def destroy
  #   @sleep_alert.destroy
  #   respond_to do |format|
  #     format.html { redirect_to sleep_alerts_url, notice: 'Sleep alert was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sleep_alert
      @sleep_alert = SleepAlert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sleep_alert_params
      params.require(:sleep_alert).permit(:user_id, :bed_time, :wake_time)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  def clock
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sleep_alerts_helper.rb
module SleepAlertsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SleepyTime</title>
    <%= csrf_meta_tags %>

    <%#= stylesheet_link_tag    'application', media: 'all' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="/styles/style.css" rel="stylesheet" type="text/css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sleep_alerts/_form.html.erb
<%= form_with(model: sleep_alert, local: true) do |form| %>
  <% if sleep_alert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sleep_alert.errors.count, "error") %> prohibited this sleep_alert from being saved:</h2>

      <ul>
      <% sleep_alert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%#= form.label :user_id %>
    <%#= form.number_field :user_id, id: :sleep_alert_user_id %>
  </div>

  <div class="field">
    <%#= form.label :bed_time %>
    <%#= form.datetime_select :bed_time, id: :sleep_alert_bed_time %>
  </div>

  <div class="field">
    <!-- <%= form.label :wake_time %> -->
    <%= form.time_select :wake_time, id: :sleep_alert_wake_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sleep_alerts/edit.html.erb
<h1>Editing Sleep Alert</h1>

<%= render 'form', sleep_alert: @sleep_alert %>

<%= link_to 'Show', @sleep_alert %> |
<%= link_to 'Back', sleep_alerts_path %>

app/views/sleep_alerts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sleep Alerts</h1>

<table>
  <!-- <thead>
    <tr>
      <th>User</th>
      <th>Bed time</th>
      <th>Wake time</th>
      <th colspan="3"></th>
    </tr>
  </thead> -->

  <tbody>
    <% @sleep_alerts.each do |sleep_alert| %>
      <tr>
        <td><%= sleep_alert.user_id %></td>
        <td><%= sleep_alert.bed_time %></td>
        <td><%= sleep_alert.wake_time %></td>
        <td><%= link_to 'Show', sleep_alert %></td>
        <td><%= link_to 'Edit', edit_sleep_alert_path(sleep_alert) %></td>
        <td><%= link_to 'Destroy', sleep_alert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sleep Alert', new_sleep_alert_path %>

app/views/sleep_alerts/new.html.erb
<img src="http://31.media.tumblr.com/5c6b9c4d077fd8b5c3977e8447f04a13/tumblr_n1tykrhm3F1sqr7kvo1_500.gif" alt="fireworks">
<br>

<%= render 'form', sleep_alert: @sleep_alert %>

<!-- <%= link_to 'Back', sleep_alerts_path %> -->

app/views/sleep_alerts/show.html.erb
<p id="notice"></p>

<p>
  <strong>The average person takes 15 minutes to fall asleep. <br> If you go to bed at the
  following bed time, <br>you should wake up at the suggested wake time.<br>And remember,</strong>
  <%= @sleep_alert.user_id %>
</p>

<img src="http://37.media.tumblr.com/d74c6badf7c5b58e59cd22eaffc64059/tumblr_n1tykrhm3F1sqr7kvo4_500.gif" alt="fireworks">
<br>

<p>
  <strong>Bed time:</strong>
  <%= @sleep_alert.bed_time %>
</p>

<p>
  <strong>Wake time:</strong>
  <%= @sleep_alert.wake_time %>
</p>

<form action=/>
    <input type="submit" value="GO BACK" />
</form>

<!-- <%= link_to 'Edit', edit_sleep_alert_path(@sleep_alert) %> |
<%= link_to 'Back', sleep_alerts_path %> -->

app/views/welcome/clock.html.erb
<h2>&#9729;&#128343; Sleep is for the Weak &#128343;&#9729;</h2>
<!-- <br>
<form action="/">
    <input type="submit" value="Go to Index" />
</form> -->

<canvas id="canvas" width="450" height="450"></canvas>

<script>
    window.onload = function () {
        setInterval(showClock, 1000);

        function showClock() {

            // DEFINE CANVAS AND ITS CONTEXT.
            var canvas = document.getElementById('canvas');
            var ctx = canvas.getContext('2d');

            var date = new Date;
            var angle;
            var secHandLength = 150;

            // CLEAR EVERYTHING ON THE CANVAS. RE-DRAW NEW ELEMENTS EVERY SECOND.
            ctx.clearRect(0, 0, canvas.width, canvas.height);

            OUTER_DIAL1();
            OUTER_DIAL2();
            //CENTER_DIAL();
            MARK_THE_HOURS();
            MARK_THE_SECONDS();

            SHOW_SECONDS();
            SHOW_MINUTES();
            SHOW_HOURS();

            function OUTER_DIAL1() {
                ctx.beginPath();
                ctx.arc(canvas.width / 2, canvas.height / 2, secHandLength + 50, 0, Math.PI * 2);
                ctx.strokeStyle = '#cc3a00';
                ctx.lineWidth = 3;
                ctx.stroke();
            }
            function OUTER_DIAL2() {
                ctx.beginPath();
                ctx.arc(canvas.width / 2, canvas.height / 2, secHandLength + 40, 0, Math.PI * 2);
                ctx.strokeStyle = '#cc3a00';
                ctx.stroke();
            }
            function CENTER_DIAL() {
                ctx.beginPath();
                ctx.arc(canvas.width / 2, canvas.height / 2, 10, 0, Math.PI * 2);
                ctx.lineWidth = 3;
                ctx.fillStyle = '#cc3a00';
                ctx.strokeStyle = '#0C3D4A';
                ctx.stroke();
            }

            function MARK_THE_HOURS() {

                for (var i = 0; i < 12; i++) {
                    angle = (i - 3) * (Math.PI * 2) / 12;       // THE ANGLE TO MARK.
                    ctx.lineWidth = 2;            // HAND WIDTH.
                    ctx.beginPath();

                    var x1 = (canvas.width / 2) + Math.cos(angle) * (secHandLength);
                    var y1 = (canvas.height / 2) + Math.sin(angle) * (secHandLength);
                    var x2 = (canvas.width / 2) + Math.cos(angle) * (secHandLength - (secHandLength / 7));
                    var y2 = (canvas.height / 2) + Math.sin(angle) * (secHandLength - (secHandLength / 7));

                    ctx.moveTo(x1, y1);
                    ctx.lineTo(x2, y2);

                    ctx.strokeStyle = '#cc3a00';
                    ctx.stroke();
                }
            }

            function MARK_THE_SECONDS() {

                for (var i = 0; i < 60; i++) {
                    angle = (i - 3) * (Math.PI * 2) / 60;       // THE ANGLE TO MARK.
                    ctx.lineWidth = 1;            // HAND WIDTH.
                    ctx.beginPath();

                    var x1 = (canvas.width / 2) + Math.cos(angle) * (secHandLength);
                    var y1 = (canvas.height / 2) + Math.sin(angle) * (secHandLength);
                    var x2 = (canvas.width / 2) + Math.cos(angle) * (secHandLength - (secHandLength / 30));
                    var y2 = (canvas.height / 2) + Math.sin(angle) * (secHandLength - (secHandLength / 30));

                    ctx.moveTo(x1, y1);
                    ctx.lineTo(x2, y2);

                    ctx.strokeStyle = '#cc3a00';
                    ctx.stroke();
                }
            }

            function SHOW_SECONDS() {

                var sec = date.getSeconds();
                angle = ((Math.PI * 2) * (sec / 60)) - ((Math.PI * 2) / 4);
                ctx.lineWidth = 0.5;              // HAND WIDTH.

                ctx.beginPath();
                // START FROM CENTER OF THE CLOCK.
                ctx.moveTo(canvas.width / 2, canvas.height / 2);
                // DRAW THE LENGTH.
                ctx.lineTo((canvas.width / 2 + Math.cos(angle) * secHandLength),
                    canvas.height / 2 + Math.sin(angle) * secHandLength);

                // DRAW THE TAIL OF THE SECONDS HAND.
                ctx.moveTo(canvas.width / 2, canvas.height / 2);    // START FROM CENTER.
                // DRAW THE LENGTH.
                ctx.lineTo((canvas.width / 2 - Math.cos(angle) * 20),
                    canvas.height / 2 - Math.sin(angle) * 20);

                ctx.strokeStyle = '#cc3a00';        // COLOR OF THE HAND.
                ctx.stroke();
            }

            function SHOW_MINUTES() {

                var min = date.getMinutes();
                angle = ((Math.PI * 2) * (min / 60)) - ((Math.PI * 2) / 4);
                ctx.lineWidth = 1.5;              // HAND WIDTH.

                ctx.beginPath();
                ctx.moveTo(canvas.width / 2, canvas.height / 2);  // START FROM CENTER.
                // DRAW THE LENGTH.
                ctx.lineTo((canvas.width / 2 + Math.cos(angle) * secHandLength / 1.1),
                    canvas.height / 2 + Math.sin(angle) * secHandLength / 1.1);

                ctx.strokeStyle = '#cc3a00';  // COLOR OF THE HAND.
                ctx.stroke();
            }

            function SHOW_HOURS() {

                var hour = date.getHours();
                var min = date.getMinutes();
                angle = ((Math.PI * 2) * ((hour * 5 + (min / 60) * 5) / 60)) - ((Math.PI * 2) / 4);
                ctx.lineWidth = 1.5;              // HAND WIDTH.

                ctx.beginPath();
                ctx.moveTo(canvas.width / 2, canvas.height / 2);     // START FROM CENTER.
                // DRAW THE LENGTH.
                ctx.lineTo((canvas.width / 2 + Math.cos(angle) * secHandLength / 1.5),
                    canvas.height / 2 + Math.sin(angle) * secHandLength / 1.5);

                ctx.strokeStyle = '#cc3a00';   // COLOR OF THE HAND.
                ctx.stroke();
            }
        }
    }
</script>

<form action=/>
    <input type="submit" value="GO BACK" />
</form>

app/views/welcome/index.html.erb
<h1>&#128564; Sleep &#128564;</h1>

What time should I go to bed?

<%#= link_to "replace me with a calculator time thing that
  uses the getTime function thing to get current time", welcome_clock_path, :class=>"button" %>

  <form action=welcome/clock>
      <input type="submit" value="TICK TOCK GUESS WHAT" />
  </form>

<br>

What time should I wake up if I go to sleep at...

<form action="/sleep_alerts/new">
  <select name="hour">
    <option value="12">12</option>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>
    <option value="6">6</option>
    <option value="7">7</option>
    <option value="8">8</option>
    <option value="9">9</option>
    <option value="10">10</option>
    <option value="11">11</option>
  </select>
  <select name="min">
    <option value="00">00</option>
    <option value="15">15</option>
    <option value="30">30</option>
    <option value="45">45</option>
  </select>
   <select name="mer">
    <option value="am">AM</option>
    <option value="pm">PM</option>
  </select><br> -->
  <input type="submit" style="font-family": 'Comic Sans MS'>
</form>

<script>
/* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
}
// Close the dropdown if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {
    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>